# This is a config for E2B sandbox template.
# You can use template ID (fwjd8t1ojskdkwxuncl1) or template name (vibe-next-test-v2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-next-test-v2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-next-test-v2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-next-test-v2')

team_id = "2134d4fe-fe2f-4e0c-825b-d1db6f09bffc"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-next-test-v2"
template_id = "fwjd8t1ojskdkwxuncl1"
